import { useEffect, useState, FormEvent } from 'react';
import { api } from '../../lib/api';

interface PortalAccess {
  id: string;
  createdAt: string;
  lastLoginAt: string | null;
  user: { id: string; email: string; isActive: boolean };
}

interface Props {
  patientId: string;
  patientFirstName: string;
  patientEmail?: string;
}

// NOTE: password is auto-generated by the server — admin never sees or sets it
const EMPTY_FORM = { email: '', firstName: '', lastName: '' };

export function PortalAccessPanel({ patientId, patientFirstName, patientEmail }: Props) {
  const [access, setAccess] = useState<PortalAccess | null>(null);
  const [hasAccess, setHasAccess] = useState(false);
  const [loading, setLoading] = useState(true);
  const [showGrantForm, setShowGrantForm] = useState(false);
  const [form, setForm] = useState({ ...EMPTY_FORM, email: patientEmail ?? '' });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const loadAccess = async () => {
    setLoading(true);
    try {
      const { data } = await api.get(`/portal/admin/access/${patientId}`);
      setHasAccess(data.hasAccess);
      setAccess(data.access);
    } catch {
      // ignore
    }
    setLoading(false);
  };

  useEffect(() => { loadAccess(); }, [patientId]);

  const handleGrant = async (e: FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError('');
    setSuccess('');
    try {
      await api.post('/portal/admin/grant', { patientId, ...form });
      setSuccess('Acceso otorgado. Se envió email de bienvenida al paciente.');
      setShowGrantForm(false);
      loadAccess();
    } catch (err: any) {
      setError(err?.response?.data?.message ?? 'Error al otorgar acceso');
    } finally {
      setSaving(false);
    }
  };

  const handleRevoke = async () => {
    if (!confirm(`¿Revocar acceso al portal de ${patientFirstName}? El paciente no podrá iniciar sesión.`)) return;
    setError('');
    setSuccess('');
    try {
      await api.delete(`/portal/admin/revoke/${patientId}`);
      setSuccess('Acceso revocado exitosamente.');
      loadAccess();
    } catch (err: any) {
      setError(err?.response?.data?.message ?? 'Error al revocar acceso');
    }
  };

  if (loading) return <div className="spinner" style={{ width: 24, height: 24, borderWidth: 2, margin: '12px 0' }} />;

  return (
    <div>
      {error && <div className="alert alert-error" style={{ marginBottom: 12 }}><span>✕</span><span>{error}</span></div>}
      {success && <div className="alert alert-success" style={{ marginBottom: 12 }}><span>✓</span><span>{success}</span></div>}

      {hasAccess && access ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          <div style={{ display: 'flex', gap: 20, fontSize: 13, flexWrap: 'wrap' }}>
            <div>
              <div style={{ color: 'var(--gray-500)', marginBottom: 2 }}>Email de acceso</div>
              <div style={{ fontWeight: 500 }}>{access.user.email}</div>
            </div>
            <div>
              <div style={{ color: 'var(--gray-500)', marginBottom: 2 }}>Estado</div>
              <span className={`badge ${access.user.isActive ? 'badge-green' : 'badge-red'}`}>
                {access.user.isActive ? 'Activo' : 'Inactivo'}
              </span>
            </div>
            {access.lastLoginAt && (
              <div>
                <div style={{ color: 'var(--gray-500)', marginBottom: 2 }}>Último acceso</div>
                <div style={{ fontWeight: 500 }}>{new Date(access.lastLoginAt).toLocaleDateString('es-AR')}</div>
              </div>
            )}
          </div>
          <div>
            <button className="btn btn-danger btn-sm" onClick={handleRevoke}>
              Revocar acceso al portal
            </button>
          </div>
        </div>
      ) : (
        <div>
          {!showGrantForm ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <span className="badge badge-gray">Sin acceso al portal</span>
              <button className="btn btn-primary btn-sm" onClick={() => setShowGrantForm(true)}>
                + Otorgar acceso
              </button>
            </div>
          ) : (
            <form onSubmit={handleGrant} className="form-grid" style={{ maxWidth: 480 }}>
              <div className="alert" style={{ background: '#eff6ff', border: '1px solid #bfdbfe', color: '#1d4ed8', borderRadius: 8, padding: '10px 14px', fontSize: 13, marginBottom: 4 }}>
                <span>🔐</span>
                <span>Se generará una contraseña temporal segura y se enviará al email del paciente. El paciente deberá cambiarla en su primer inicio de sesión.</span>
              </div>
              <div className="form-row">
                <div className="form-group">
                  <label>Nombre *</label>
                  <input value={form.firstName} onChange={(e) => setForm(f => ({ ...f, firstName: e.target.value }))} required />
                </div>
                <div className="form-group">
                  <label>Apellido *</label>
                  <input value={form.lastName} onChange={(e) => setForm(f => ({ ...f, lastName: e.target.value }))} required />
                </div>
              </div>
              <div className="form-group">
                <label>Email de acceso *</label>
                <input type="email" value={form.email} onChange={(e) => setForm(f => ({ ...f, email: e.target.value }))} required />
              </div>
              <div style={{ display: 'flex', gap: 10 }}>
                <button type="submit" className="btn btn-primary btn-sm" disabled={saving}>
                  {saving ? 'Guardando...' : 'Otorgar acceso'}
                </button>
                <button type="button" className="btn btn-secondary btn-sm" onClick={() => setShowGrantForm(false)}>
                  Cancelar
                </button>
              </div>
            </form>
          )}
        </div>
      )}
    </div>
  );
}
